alias c="clear"
alias cd="z"
alias cdi="zi"
alias dotfiles="git --git-dir=$HOME/.files/ --work-tree=$HOME"
alias ld="lazygit -g .files -w $HOME"
alias lg="lazygit"
alias n="nvim"
alias n2="/Users/conor/Desktop/nvim-macos-arm64/bin/nvim"
alias srcz="source $ZDOTDIR/.zshrc"
alias t="tree"
alias venvls="ls -l ~/workspace/venvs/"
alias x="exit"
